version: '3.8'

services:
  server:
    build: ./server
    container_name: nexus_server
    restart: always
    network_mode: "host"
    env_file: ./server/.env
    volumes:
      - ./server/uploads:/app/uploads

  client:
    build: ./client
    container_name: nexus_client
    restart: always
    network_mode: "host"
    environment:
      - VITE_API_URL=http://localhost:5001/api
      - VITE_SOCKET_URL=http://localhost:5001
    stdin_open: true
    tty: true
